<a href="https://colab.research.google.com/github/abhi221a/FreeCodeCamp/blob/main/Intro_to_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
string = tf.Variable("This isa string", tf.string)

In [5]:
number = tf.Variable(324, tf.int16)

In [6]:
floating = tf.Variable(3.567, tf.float64)

## Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor.What we created above is a tensor of rank 0, also known as scalar.

Now we'll create some tensors of higher degrees

In [12]:
rank1_tensor = tf.Variable(["test", "ok","tim"], tf.string)

In [10]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

To determine the rank of a tensor we can call the following method

In [11]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

##Shape of Tensors

Now that we've talked about the rank of tensors its time to talk about the shape. The shape of a tensor is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unkown.

To get the shape of a tensor we use the shape attribute.

In [15]:
rank2_tensor.shape

TensorShape([2, 2])

## Changing the Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convinient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [19]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones [1 list, inside, we have 2 list, inside each interior list, we have 3 elements]
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in the place
                                       # this will reshape the tensor to [3,2]

#the number of elements in the reshaped tansor MUST match the number in the original

Now let's have a look at our different tensors.

In [17]:
print(tensor1)
print(tensor2)
print(tensor3)

# NOtice tha changes in the shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Type of Tensors

Before we go to far I will mention that there are different types of tensors. These are the most commonly used and we will talk more in depth about each as they are used.

  

*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of Variable all of these tensors are immuttable, meaning their value may not change during execution. For now it is sufficient to understand that we use the Variable tensor when we want to potentially change that value of our tensor.






## Evaluating Tensors

There will be some times throughout this guide that we need to evaluate a tensor. In other words, get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a _session_ to evaluate the tensor.
There are many different ways to achieve this but I will note the simplest way bellow.

In [ ]:
with tf.Session() as sess:  # creates a session using the default graph
  tensor.eval()     # tensor will of course be the name of your tensor

In the code above we evaluated the tensor variable that was stored in the **default graph**. The default graph holds all operations not specified to any other graph. It is possible to create our own seperate graphs but now we will stick with the default.